Delete providers.tf
Run terraform init -backend=false

Initializing modules...
- databricks in modules/databricks
╷
│ Error: Duplicate required providers configuration
│
│   on providers.tf line 2, in terraform:
│    2:   required_providers {
│
│ A module may have only one required providers configuration. The required
│ providers were previously configured at main.tf:2,3-21.
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.