Fix
Initializing modules...
- databricks in modules/databricks
╷
│ Error: Duplicate required providers configuration
│
│   on main.tf line 25, in terraform:
│   25:   required_providers {
│
│ A module may have only one required providers configuration. The required
│ providers were previously configured at main.tf:2,3-21.
╵
╷
│ Error: Duplicate output definition
│
│   on modules/databricks/outputs.tf line 1:
│    1: output "databricks_workspace_url" {
│
│ An output named "databricks_workspace_url" was already defined at
│ modules/databricks/main.tf:22,1-34. Output names must be unique within a
│ module.
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.