Fixes
0s
Run terraform validate
╷
│ Error: Reference to undeclared resource
│
│   on modules/databricks/main.tf line 33, in resource "azurerm_subnet_network_security_group_association" "private":
│   33:   subnet_id                 = azurerm_subnet.private.id                 # ID of the private subnet
│
│ A managed resource "azurerm_subnet" "private" has not been declared in
│ module.databricks.
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.